import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import Marquee from 'react-fast-marquee';

import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import 'react-awesome-slider/dist/styles.css';

import Footer from '../components/Footer.js';

import 'bulma/css/bulma.css';

import { FaArrowUp } from "react-icons/fa";
import { FaArrowDown } from "react-icons/fa";


export default function Home() {

  const AutoplaySlider = withAutoplay(AwesomeSlider);

  const [warnLang, setWarnLand] = useState(1);
  const [descLang, setDescLang] = useState(1);
  const [aboutLang, setAboutLang] = useState(1);

  const [data, setData] = useState(null);

  const url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=15&page=1&sparkline=false';

  useEffect(() => {
    axios.get(url).then((response) => {
      setData(response.data)
    }).catch((error) => {
      console.log(error)
    })
  }, [])

  console.log(data);

  if(!data) return null;

  return (
    <div className="w-full">
      <Head>
        <title>Sokudo Lottery | Ethereum Lottery dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative min-h-full w-full">
      {/* navbar */}
        <nav className="w-full mb-4 absolute z-50 top-0">
          <div className="flex justify-between items-center w-full max-w-7xl mx-auto p-3 mt-0 mt-4">
            <div className="">
                <h1 className="font-[Starduster] text-4xl text-customYellow drop-shadow-lg drop-shadow-lg">SOKUDO</h1>
            </div>
            <div className="hidden p-2 bg-purple-500 font-[Starduster] text-xl text-yellow-300 cursor-pointer drop-shadow-lg">
              <button className="font-[Starduster] cursor-pointer">
                Connect Wallet
              </button>
            </div>
          </div>
        </nav>

        {/* main content */}
        <div className="mt-12 md:mt-0 w-full absolute z-50 min-h-full">
          <div className="w-full max-w-7xl mx-auto flex flex-col md:flex-row h-screen justify-center items-center p-3">
            <div className="w-full md:w-1/2 flex flex-col justify-start items-center">
              <section className="w-full">
                <h2 className="hidden md:block font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg">SOKUDO</h2>
                <h4 className="font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg mb-4">Lottery</h4>
                <div className="hidden md:flex md:h-24 overflow-hidden mb-4">
                  <div className="animate-[titleMove_10s_ease-in_infinite]">
                  <h4 className="font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg mb-4">宝くじ</h4>
                  <h4 className="font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg mb-4">Lotterie</h4>
                  <h4 className="font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg mb-4">лотерея</h4>
                  <h4 className="font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg mb-4">վիճակախաղ</h4>
                  <h4 className="font-[Starduster] text-4xl md:text-8xl text-customYellow drop-shadow-lg mb-4">लॉटरी</h4>
                  </div>
                </div>
                <h1 className="text-2xl font-[Starduster] text-customYellow mb-8">Ethereum Lottery dApp</h1>
              </section>
              <section className="flex w-2/3 md:w-full flex-col md:flex-row">
                <div className="md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
                  <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                    <p className="text-customYellow text-2xl text-center">To Lottery</p>
                  </Link>
                </div>
                <div className="text-center bg-customBlue font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightBlue">
                  <button href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow p-2">
                    LeArn More
                  </button>
                </div>
              </section>
            </div>
            <div className="w-full md:w-1/2 h-full flex flex-col justify-center items-center relative">
              <div className="w-3/4 flex justify-center items-center animate-[modelBeep_15s_ease-in-out_infinite]">
                <img src="/images/pinup1.png" className="h-full w-full" />
              </div>
              <div className="hidden md:flex flex-col absolute top-20 right-0 z-100">
                <h4 className="text-4xl text-customYellow font-[Starduster] drop-shadow-lg animate-[beep1_10s_ease-in-out_infinite]">Good Luck!</h4>
                <h4 className="text-4xl text-customYellow font-[Starduster] drop-shadow-lg animate-[beep2_10s_ease-in-out_infinite]">幸運を祈る</h4>
              </div>
            </div>
            <div className="w-full h-12 bg-customYellow absolute z-100 bottom-20 overflow-hidden flex items-center">
              <Marquee pauseOnHover speed={80} gradient={false}>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[0].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[0].current_price.toLocaleString()}
                  </h4>
                  {data[0].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[0].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[0].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[1].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[1].current_price.toLocaleString()}
                  </h4>
                  {data[1].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[1].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[1].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[2].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[2].current_price.toLocaleString()}
                  </h4>
                  {data[2].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[2].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[2].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[3].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[3].current_price.toLocaleString()}
                  </h4>
                  {data[3].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[3].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[3].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[4].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[4].current_price.toLocaleString()}
                  </h4>
                  {data[4].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[4].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[4].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[5].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[5].current_price.toLocaleString()}
                  </h4>
                  {data[5].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[5].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[5].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[6].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[6].current_price.toLocaleString()}
                  </h4>
                  {data[6].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[6].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[6].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[7].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[7].current_price.toLocaleString()}
                  </h4>
                  {data[7].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[7].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[7].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[8].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[8].current_price.toLocaleString()}
                  </h4>
                  {data[8].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[8].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[8].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[9].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[9].current_price.toLocaleString()}
                  </h4>
                  {data[9].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[9].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[9].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[10].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[10].current_price.toLocaleString()}
                  </h4>
                  {data[10].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[10].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[10].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[11].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[11].current_price.toLocaleString()}
                  </h4>
                  {data[11].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[11].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[11].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[12].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[12].current_price.toLocaleString()}
                  </h4>
                  {data[12].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[12].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[12].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    {data[13].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[13].current_price.toLocaleString()}
                  </h4>
                  {data[13].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[13].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[13].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

                <div className="flex items-center mx-8">
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] ml-4 mr-2">
                    {data[14].symbol.toUpperCase()} :
                  </h4>
                  <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mr-2">
                    ${data[14].current_price.toLocaleString()}
                  </h4>
                  {data[14].price_change_percentage_24h < 0 ? (
                    <h4 className="text-2xl font-bold text-customRed font-[Starduster]"><FaArrowDown className="inline -mt-2" />{data[14].price_change_percentage_24h.toFixed(2)}</h4>
                  ) : (
                    <h4 className="text-2xl font-bold text-customBlue font-[Starduster]"><FaArrowUp className="inline -mt-2" />{data[14].price_change_percentage_24h.toFixed(2)}</h4>
                  )}
                </div>

              </Marquee>
            </div>
          </div>
        </div>
        {/* timestamp: 20:00 */}

        <div className="w-full h-screen">
          <Image
            src="/images/background.png"
            layout="fill"
            objectFit="cover"
          />
        </div>
      </main>

      {/* about */}
      <div className="w-full bg-customBlue py-8">
        <div className="w-full">
          <div className="w-full max-w-7xl mx-auto flex justify-center items-center flex-col md:flex-row mb-4 bg-zinc-800 rounded-xl border-4 border-customLightBlue drop-shadow-xl">
            <div className="w-full md:w-1/2 p-4">

            <div className="w-full flex flex-col mb-4">
              <h4 className="text-2xl font-[Starduster] text-customRed">lAnguAge Selection</h4>
              <div className="w-full flex">
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setWarnLand(1)}>En</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setWarnLand(2)}>Ja</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setWarnLand(3)}>Hi</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setWarnLand(4)}>Hu</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setWarnLand(5)}>Tr</button>
              </div>
            </div>
            { warnLang == 1 &&
              <div className="w-full">
                <h3 className="text-2xl text-customRed font-[Starduster]">importAnt!</h3>
                <p className="text-white">
                  Sokudo Lottery uses testnet Ether only and is deployed to the Rinkeby testnet.
                </p>
                <p className="text-white">
                  No real value is required to participate in the lottery.
                </p>
                <p className="text-white">
                  No real value is to be gained or distributed as the prize for winning and/or participating in this lottery.
                </p>
                <p className="text-white">
                  This project exists for demonstration purposes only.
                </p>
              </div>
            }

            { warnLang == 2 &&
              <div className="w-full">
                <h3 className="text-2xl text-customRed font-[Starduster] font-bold">重要!</h3>
                <p className="text-white">
                  SokudoLotteryはtestnetEtherのみを使用し、Rinkebyテストネットに展開されます.
                </p>
                <p className="text-white">
                  宝くじに参加するのに実際の価値は必要ありません.
                </p>
                <p className="text-white">
                  この宝くじの当選および/または参加の賞品として、実際の価値を獲得または分配することはできません。.
                </p>
                <p className="text-white">
                  このプロジェクトは、デモンストレーション目的でのみ存在します。
                </p>
              </div>
            }

            { warnLang == 3 &&
              <div className="w-full">
                <h3 className="text-2xl text-customRed font-[Starduster] font-bold">जरूरी!</h3>
                <p className="text-white">
                  सोकुडो लॉटरी केवल टेस्टनेट ईथर का उपयोग करती है और इसे रिंकीबी टेस्टनेट पर तैनात किया जाता है।
                </p>
                <p className="text-white">
                  लॉटरी में भाग लेने के लिए किसी वास्तविक मूल्य की आवश्यकता नहीं है।
                </p>
                <p className="text-white">
                  इस लॉटरी में जीतने और/या भाग लेने के लिए पुरस्कार के रूप में कोई वास्तविक मूल्य प्राप्त या वितरित नहीं किया जाना है।
                </p>
                <p className="text-white">
                  यह परियोजना केवल प्रदर्शन उद्देश्यों के लिए मौजूद है।
                </p>
              </div>
            }

            { warnLang == 4 &&
              <div className="w-full">
                <h3 className="text-2xl text-customRed font-[Starduster]">fontos!</h3>
                <p className="text-white">
                  A Sokudo Lottery csak a testnet Ether-t használja, és a Rinkeby teszthálózatra van telepítve.
                </p>
                <p className="text-white">
                  A sorsoláson való részvételhez nincs szükség valós értékre.
                </p>
                <p className="text-white">
                  A lottón nyerésért és/vagy részvételért valódi értéket nem lehet nyerni vagy kiosztani.
                </p>
                <p className="text-white">
                  Ez a projekt csak demonstrációs célokat szolgál.
                </p>
              </div>
            }

            { warnLang == 5 &&
              <div className="w-full">
                <h3 className="text-2xl text-customRed font-[Starduster]">önemli!</h3>
                <p className="text-white">
                  Sokudo Piyango yalnızca test ağı Ether'i kullanır ve Rinkeby test ağına dağıtılır.
                </p>
                <p className="text-white">
                  Piyangoya katılmak için gerçek bir değer gerekli değildir.
                </p>
                <p className="text-white">
                  Bu piyangoyu kazanmanın ve/veya katılmanın ödülü olarak gerçek bir değer kazanılamaz veya dağıtılamaz.
                </p>
                <p className="text-white">
                  Bu proje sadece tanıtım amaçlıdır.
                </p>
              </div>
            }

            </div>
            <div className="w-full md:w-1/2 p-4">
              <div className="w-full flex justify-center items-center">
                <div className="w-1/2 flex justify-center items-center">
                  <Image
                    src="/images/warning.png"
                    width={100}
                    height={100}
                  />
                </div>
                <div className="w-1/2">
                  <div className="h-8 overflow-hidden mb-4">
                    <div className="animate-[warningMove2_10s_ease-in_infinite_alternate]">
                      <h4 className="text-4xl text-customRed font-[Starduster]">wArning</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster] font-bold">警告</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">WArnung</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">Figyelem</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster] font-bold">경고</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">upozorenje</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">uyAri</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">Avviso</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster] font-bold">चेतावनी</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">bridinAjums</h4>
                    </div>
                  </div>
                  <div className="h-16 overflow-hidden mb-4">
                    <div className="animate-[warningMove_10s_ease-in_infinite_alternate]">
                      <h5 className="text-2xl text-customRed font-[Starduster]">for testing purposes only</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster] font-bold">テスト目的のみ</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">nur zu Testzwecken</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">csAk tesztelés céljából</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster] font-bold">테스트 목적으로만</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">sAmo zA svrhe testirAnjA</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">sAdece test AmAçli</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">solo A scopo di test</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster] font-bold">केवल परीक्षण के उद्देश्य</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">tikAi testešAnAs nolukiem</h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* instructions */}
        <div className="w-full mb-8">
          <div className="w-full max-w-7xl mx-auto flex flex-col md:flex-row mb-4">
            <div className="w-full md:w-1/2 p-4 rounded-xl border-0 border-customLightBlue drop-shadow-xl bg-white">

              <div className="w-full flex flex-col mb-4">
                <h4 className="text-2xl font-[Starduster] text-customRed">lAnguAge Selection</h4>
                <div className="w-full flex">
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(1)}>En</button>
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(2)}>Ja</button>
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(3)}>Hi</button>
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(4)}>Hu</button>
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(5)}>Tr</button>
                </div>
              </div>

              { descLang == 1 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">How to Use</h3>
                <p>
                  Hello, I am Sindi. I will be your virtual host.
                </p>
                <p>
                  You are going to need a MetaMask wallet, if you don't have one installed yet you can download it here:
                </p>
                <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
                <p>
                  Sokudo Lottery is connected to the Rinkeby ether testnet, so you should connect your MetaMask wallet to
                  Rinkeby testnet.
                </p>
                <p>
                  Sokudo Lottery uses testnet Ether which you can get in one of the Rinkeby testnet faucets:
                </p>
                <ul className="mb-4">
                  <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
                  <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
                  <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
                </ul>
                <p>
                  Once you get test Ether you are ready to play!
                </p>
                <p className="mb-4">
                  Click here to go to lottery, good luck!
                </p>
                <div className="w-full md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
                  <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                    <p className="text-customYellow text-2xl text-center">To Lottery</p>
                  </Link>
                </div>
              </div>
            }

            { descLang == 2 &&
            <div className="w-full">
              <h3 className="text-2xl text-customPurple font-[Starduster]">それの使い方</h3>
              <p>
                こんにちは、シンディです, 私があなたのホストになります
              </p>
              <p>
                MetaMaskウォレットが必要になります, <br />こちらからダウンロードできます:
              </p>
              <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
              <p>
                宝くじはネットワークRinkebyに接続されています, <br />
                MetaMaskをRinkebyネットワークに接続します.
              </p>
              <p>
                宝くじはtest Etherを使用します<br />
                ここで test Ether を入手できます:
              </p>
              <ul className="mb-4">
                <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
                <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
                <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
              </ul>
              <p>
                これで、プレイする準備ができました!
              </p>
              <p className="mb-4">
                宝くじに行くにはここをクリックしてください!
              </p>
              <div className="w-full md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
                <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                  <p className="text-customYellow text-2xl text-center">宝くじに行く</p>
                </Link>
              </div>
            </div>
          }

          { descLang == 3 &&
          <div className="w-full">
            <h3 className="text-2xl text-customPurple font-[Starduster]">कैसे इस्तेमाल करे</h3>
            <p>
              हैलो, मैं सिंधी हूँ, मैं आपका मेजबान बनूंगा.
            </p>
            <p>
              आपको मेटामास्क वॉलेट की आवश्यकता होगी, <br />
              आप द्वारा इसे यहां पर डाउनलोड किया जा सकता है:
            </p>
            <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
            <p>
              सोकुडो लॉटरी रिकेबी टेस्टनेट से जुड़ी है, <br />
              अपने मेटामास्क को रिंकीबी से कनेक्ट करें
            </p>
            <p>
              सोकुडो लॉटरी टेस्ट ईथर का उपयोग करती है, <br />
              आप इसे यहां पा सकते हैं:
            </p>
            <ul className="mb-4">
              <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
              <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
              <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
            </ul>
            <p>
              अब, आप खेलने के लिए तैयार हैं!
            </p>
            <p className="mb-4">
              लॉटरी में जाने के लिए यहां क्लिक करें, आप सौभाग्यशाली हों!
            </p>
            <div className="w-full md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
              <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                <p className="text-customYellow text-2xl text-center">लॉटरी में जाना</p>
              </Link>
            </div>
          </div>
        }

        { descLang == 4 &&
        <div className="w-full">
          <h3 className="text-2xl text-customPurple font-[Starduster]">hogyAn kell hAsznAlni</h3>
          <p>
            Hello, Sindi vagyok, én leszek a házigazdád.
          </p>
          <p>
            Szüksége lesz egy MetaMask pénztárcára, ezt itt tudod letölteni:
          </p>
          <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
          <p>
            A Sokudo Lottery csatlakozik a Rinkeby ether teszthálózathoz, csatlakoztassa a MetaMask pénztárcáját a Rinkeby testnethez.
          </p>
          <p>
            A Sokudo Lottery a testnet Ethert használja, itt kaphatod meg:
          </p>
          <ul className="mb-4">
            <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
            <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
            <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
          </ul>
          <p>
            Most készen áll a játékra!
          </p>
          <p className="mb-4">
            kattintson ide a játékhoz. Sok szerencsét!
          </p>
          <div className="w-full md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
            <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
              <p className="text-customYellow text-2xl text-center">menj lottózni</p>
            </Link>
          </div>
        </div>
      }

      { descLang == 5 &&
      <div className="w-full">
        <h3 className="text-2xl text-customPurple font-[Starduster]">bu nAsil kullAnilir</h3>
        <p>
          Merhaba ben Sindi, senin ev sahibin olacağım.
        </p>
        <p>
          Bir MetaMask cüzdanına ihtiyacınız olacak, buradan indirebilirsiniz:
        </p>
        <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
        <p>
          Sokudo Piyango, Rinkeby ether test ağına bağlı, MetaMask cüzdanınızı Rinkeby testnet'e bağlayın.
        </p>
        <p>
          Sokudo Piyango testnet Ether kullanıyor. Buradan alabilirsin:
        </p>
        <ul className="mb-4">
          <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
          <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
          <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
        </ul>
        <p>
          Oynamaya hazırsın!
        </p>
        <p className="mb-4">
          Piyangoya gitmek için buraya tıklayın, iyi şanslar!
        </p>
        <div className="w-full md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
          <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
            <p className="text-customYellow text-2xl text-center">piyAngoyA git</p>
          </Link>
        </div>
      </div>
    }


            </div>
            <div className="w-full md:w-1/2">
              <div className="w-full flex justify-center md:justify-start items-center relative">
                <div className="hidden md:flex w-2/3">
                  <img src="/images/assistent1.png" className="h-full w-full" />
                </div>
                <div className="flex w-2/3 md:hidden">
                  <img src="/images/assistent3.png" className="h-full w-full" />
                </div>
                <div className="hidden md:block absolute top-10 right-10 text-right">
                  <h4 className="font-[Starduster] text-customYellow text-4xl drop-shadow-lg animate-[beep1_10s_ease-in-out_infinite]">Welcome</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl font-bold drop-shadow-lg animate-[beep2_10s_ease-in-out_infinite]">ようこそ</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl font-bold drop-shadow-lg animate-[beep3_10s_ease-in-out_infinite]">स्वागत</h4>
                </div>
                <div className="hidden md:block absolute bottom-0 right-10 text-right">
                  <h4 className="font-[Starduster] text-customYellow text-4xl font-bold drop-shadow-lg animate-[beep1_10s_ease-in-out_infinite]">어서 오십시오</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl drop-shadow-lg animate-[beep2_10s_ease-in-out_infinite]">Üdvözöljük</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl drop-shadow-lg animate-[beep3_10s_ease-in-out_infinite]">Hos geldin</h4>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* description */}
        <div className="w-full">
          <div className="w-full max-w-7xl mx-auto flex flex-col-reverse md:flex-row pb-4">
            <div className="w-full md:w-1/2">
              <div className="w-full flex justify-center md:justify-end items-center relative">
                <div className="hidden md:flex w-2/3">
                  <img src="/images/assistent4.png" className="h-full w-full" />
                </div>
                <div className="flex w-2/3 md:hidden">
                  <img src="/images/assistent5.png" className="h-full w-full" />
                </div>
                <div className="hidden md:block absolute top-10 left-10 text-left">
                  <h4 className="font-[Starduster] text-customYellow text-4xl drop-shadow-lg animate-[beep1_10s_ease-in-out_infinite]">Welcome</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl font-bold drop-shadow-lg animate-[beep2_10s_ease-in-out_infinite]">ようこそ</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl font-bold drop-shadow-lg animate-[beep3_10s_ease-in-out_infinite]">स्वागत</h4>
                </div>
                <div className="hidden md:block absolute bottom-0 left-10 text-left">
                  <h4 className="font-[Starduster] text-customYellow text-4xl font-bold drop-shadow-lg animate-[beep1_10s_ease-in-out_infinite]">어서 오십시오</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl drop-shadow-lg animate-[beep2_10s_ease-in-out_infinite]">Üdvözöljük</h4>
                  <h4 className="font-[Starduster] text-customYellow text-4xl drop-shadow-lg animate-[beep3_10s_ease-in-out_infinite]">Hos geldin</h4>
                </div>
              </div>
            </div>
            <div className="w-full md:w-1/2 p-4 rounded-xl border-0 border-customLightBlue drop-shadow-xl bg-white">

            <div className="w-full flex flex-col mb-4">
              <h4 className="text-2xl font-[Starduster] text-customRed">lAnguAge Selection</h4>
              <div className="w-full flex">
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setAboutLang(1)}>En</button>
                <button className="p-2 px-4 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setAboutLang(2)}>Ja</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setAboutLang(3)}>Hi</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setAboutLang(4)}>Hu</button>
                <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setAboutLang(5)}>Tr</button>
              </div>
            </div>

            { aboutLang == 1 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">About</h3>
                <p className="mb-2">
                  This project is made using smart contract written in Solidity and Truffle. Frontend is made with Next.Js and Tailwing css
                </p>
                <p>
                  Project also features real-time prices of top 15 cryptocurrencies, using Coingecko API.
                </p>
                <a href="https://www.coingecko.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">coingecko.com</a>
                <p className="mb-2">
                  UI design was heavily inspired by the visual style of Blade Runner and Cyberpunk genre, <br />
                  one key feature of such style is the presence of multitude of languages mashed together to form a vibrant,
                  multicultural futuristic setting.
                </p>
                <p className="mb-2">
                  Since the author of this dApp is not a proficient linguist, he did the best he could using Google translate and similar
                  translation services while writting the text. Therefor, apologies for any grammar mistakes which are surely present.
                </p>
                <p>
                  Character "Sindi" was created by insanely talented artist:
                </p>
                <a href="https://verymanytubes.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">verymanytubes.com</a>
                <div className="bg-transparent">
                  <AutoplaySlider
                      play={true}
                      cancelOnInteraction={false} // should stop playing on user interaction
                      interval={3000}
                      organicArrows={false}
                      bullets={false}
                      sliderHeightPercentage={10}
                      className="h-20"
                    >
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                  </AutoplaySlider>
                </div>
              </div>
            }

            { aboutLang == 2 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">プロジェクトについて</h3>
                <p className="mb-2">
                  このプロジェクトは、SolidityとTruffleで書かれたスマートコントラクトを使用して作成されています. フロントエンドはNext.JsとTailwingcssで作られています
                </p>
                <p>
                  プロジェクトはまた、Coingecko APIを使用して、上位15の暗号通貨のリアルタイム価格を特徴としています。
                </p>
                <a href="https://www.coingecko.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">coingecko.com</a>
                <p className="mb-2">
                  UIデザインは、ブレードランナーとサイバーパンクのジャンルの視覚スタイルに大きく影響を受けました <br />
                  このようなスタイルの重要な特徴の1つは、活気に満ちた多文化の未来的な設定を形成するために多数の言語がマッシュアップされていることです。
                </p>
                <p className="mb-2">
                  このdAppの作成者は熟練した言語学者ではないため、テキストを書きながら、Google翻訳や同様の翻訳サービスを使用してできる限りのことをしました。<br />
                  そのため、確かに存在する文法の間違いについてお詫び申し上げます。
                </p>
                <p>
                  キャラクター「シンディ」は素晴らしい才能のあるアーティストによって作られました：
                </p>
                <a href="https://verymanytubes.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">verymanytubes.com</a>
                <div className="bg-transparent">
                  <AutoplaySlider
                      play={true}
                      cancelOnInteraction={false} // should stop playing on user interaction
                      interval={3000}
                      organicArrows={false}
                      bullets={false}
                      sliderHeightPercentage={10}
                      className="h-20"
                    >
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                  </AutoplaySlider>
                </div>
              </div>
            }

            { aboutLang == 3 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">इस परियोजना के बारे में</h3>
                <p className="mb-2">
                  यह प्रोजेक्ट सॉलिडिटी और ट्रफल में लिखे स्मार्ट कॉन्ट्रैक्ट का उपयोग करके बनाया गया है। फ़्रंटएंड Next.Js और Tailwing css के साथ बनाया गया है.
                </p>
                <p>
                  प्रोजेक्ट में Coingecko API का उपयोग करते हुए शीर्ष 15 क्रिप्टोकरेंसी की रीयल-टाइम कीमतें भी शामिल हैं।
                </p>
                <a href="https://www.coingecko.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">coingecko.com</a>
                <p className="mb-2">
                  UI डिज़ाइन ब्लेड रनर और साइबरपंक शैली की दृश्य शैली से बहुत अधिक प्रेरित था, <br />
                  इस तरह की शैली की एक प्रमुख विशेषता एक जीवंत, बहुसांस्कृतिक भविष्यवादी सेटिंग बनाने के लिए एक साथ कई भाषाओं की उपस्थिति है।.
                </p>
                <p className="mb-2">
                  इस डीएपी के लेखक एक कुशल भाषाविद् नहीं हैं, पाठ लिखते समय उन्होंने Google अनुवाद और इसी तरह की अनुवाद सेवाओं का उपयोग करने के लिए हर संभव प्रयास किया.
                  इसलिए, किसी भी व्याकरण की गलतियों के लिए क्षमा चाहते हैं जो निश्चित रूप से मौजूद हैं।
                </p>
                <p>
                  चरित्र "सिंडी" अद्भुत प्रतिभाशाली कलाकार द्वारा बनाया गया था:
                </p>
                <a href="https://verymanytubes.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">verymanytubes.com</a>
                <div className="bg-transparent">
                  <AutoplaySlider
                      play={true}
                      cancelOnInteraction={false} // should stop playing on user interaction
                      interval={3000}
                      organicArrows={false}
                      bullets={false}
                      sliderHeightPercentage={10}
                      className="h-20"
                    >
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                  </AutoplaySlider>
                </div>
              </div>
            }

            { aboutLang == 4 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">Errol A Projektrol</h3>
                <p className="mb-2">
                  Ez a projekt Solidity és Truffle nyelven írt intelligens szerződéssel készült. A frontend Next.Js és Tailwing css segítségével készült.
                </p>
                <p>
                  A projekt a Coingecko API használatával a 15 legnépszerűbb kriptovaluta valós idejű árait is tartalmazza.
                </p>
                <a href="https://www.coingecko.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">coingecko.com</a>
                <p className="mb-2">
                  A felhasználói felület kialakítását erősen a Blade Runner és a Cyberpunk műfaj vizuális stílusa ihlette, <br />
                  Ennek a stílusnak az egyik legfontosabb jellemzője a sokféle nyelv jelenléte, amelyek egy élénk, multikulturális futurisztikus környezetet alkotnak.
                </p>
                <p className="mb-2">
                  Mivel ennek a dApp-nak a szerzője nem jártas nyelvész, minden tőle telhetőt megtett a Google fordító és a hasonló fordítói szolgáltatások segítségével a szövegírás közben.
                  Ezért elnézést a nyelvtani hibákért, amelyek biztosan előfordulnak.
                </p>
                <p>
                  A "Sindi" karaktert egy csodálatos tehetséges művész készítette:
                </p>
                <a href="https://verymanytubes.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">verymanytubes.com</a>
                <div className="bg-transparent">
                  <AutoplaySlider
                      play={true}
                      cancelOnInteraction={false} // should stop playing on user interaction
                      interval={3000}
                      organicArrows={false}
                      bullets={false}
                      sliderHeightPercentage={10}
                      className="h-20"
                    >
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                  </AutoplaySlider>
                </div>
              </div>
            }

            { aboutLang == 5 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">bu proje hAkkindA</h3>
                <p className="mb-2">
                  Bu proje, Solidity ve Truffle ile yazılmış akıllı sözleşme kullanılarak yapılmıştır. Frontend, Next.Js ve Tailwing css ile yapılır.
                </p>
                <p>
                  Proje ayrıca Coingecko API'sini kullanarak en iyi 15 kripto para biriminin gerçek zamanlı fiyatlarını da sunuyor.
                </p>
                <a href="https://www.coingecko.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">coingecko.com</a>
                <p className="mb-2">
                  UI tasarımı, Blade Runner ve Cyberpunk türünün görsel tarzından büyük ölçüde ilham aldı, <br />
                  Bu tarz bir tarzın temel özelliklerinden biri, canlı, çok kültürlü fütüristik bir ortam oluşturmak için bir araya getirilmiş çok sayıda dilin varlığıdır.
                </p>
                <p className="mb-2">
                  Bu dApp'nin yazarı yetkin bir dilbilimci değil, metni yazarken Google çeviri ve benzeri çeviri hizmetlerini kullanarak elinden gelenin en iyisini yaptı. Bu nedenle, kesinlikle mevcut olan herhangi bir dilbilgisi hatası için özür dilerim.
                </p>
                <p>
                  "Sindi" karakteri, inanılmaz yetenekli bir sanatçı tarafından yapıldı:
                </p>
                <a href="https://verymanytubes.com/" className="font-bold text-customPurple transition duration-300 hover:text-customBlue">verymanytubes.com</a>
                <div className="bg-transparent">
                  <AutoplaySlider
                      play={true}
                      cancelOnInteraction={false} // should stop playing on user interaction
                      interval={3000}
                      organicArrows={false}
                      bullets={false}
                      sliderHeightPercentage={10}
                      className="h-20"
                    >
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                    <div className="bg-transparent" data-src="/images/pinup1.png" />
                  </AutoplaySlider>
                </div>
              </div>
            }

            </div>
          </div>
        </div>
      </div>

      <div className="w-full bg-customPurple">
        <Footer />
      </div>
    </div>
  )
}
