import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Marquee from 'react-fast-marquee';

import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';
import 'react-awesome-slider/dist/styles.css';

import Footer from '../components/Footer.js';

import 'bulma/css/bulma.css';

export default function Home() {

  const AutoplaySlider = withAutoplay(AwesomeSlider);

  const [descLang, setDescLang] = useState(1);

  return (
    <div className="w-full">
      <Head>
        <title>Sokudo Lottery | Ethereum Lottery dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative min-h-full w-full">
      {/* navbar */}
        <nav className="w-full mb-4 absolute z-50 top-0">
          <div className="flex justify-between items-center w-full max-w-7xl mx-auto p-3 mt-4">
            <div className="">
                <h1 className="font-[Starduster] text-4xl text-yellow-300 drop-shadow-lg drop-shadow-lg">SOKUDO</h1>
            </div>
            <div className="hidden p-2 bg-purple-500 font-[Starduster] text-xl text-yellow-300 cursor-pointer drop-shadow-lg">
              <button className="font-[Starduster] cursor-pointer">
                Connect Wallet
              </button>
            </div>
          </div>
        </nav>

        {/* main content */}
        <div className="w-full absolute z-50 min-h-full">
          <div className="w-full max-w-7xl mx-auto flex flex-col md:flex-row h-screen justify-center items-center p-3">
            <div className="w-full md:w-1/2 flex flex-col justify-start items-center">
              <section className="w-full">
                <h2 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg">SOKUDO</h2>
                <h4 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg mb-4">Lottery</h4>
                <div className="h-24 overflow-hidden mb-4">
                  <div className="animate-[titleMove_10s_ease-in_infinite]">
                  <h4 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg mb-4">宝くじ</h4>
                  <h4 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg mb-4">Lotterie</h4>
                  <h4 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg mb-4">лотерея</h4>
                  <h4 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg mb-4">վիճակախաղ</h4>
                  <h4 className="font-[Starduster] text-8xl text-customYellow drop-shadow-lg mb-4">लॉटरी</h4>
                  </div>
                </div>
                <h1 className="text-2xl font-[Starduster] text-customYellow mb-8">Ethereum Lottery dApp</h1>
              </section>
              <section className="flex w-1/2 md:w-full flex-col md:flex-row">
                <div className="md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
                  <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                    <p className="text-customYellow text-2xl text-center">To Lottery</p>
                  </Link>
                </div>
                <div className="text-center p-2 bg-customBlue font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightBlue">
                  <button href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                    LeArn More
                  </button>
                </div>
              </section>
            </div>
            <div className="w-full md:w-1/2 h-full flex flex-col justify-center items-center relative">
              <div className="w-3/4 flex justify-center items-center animate-[modelBeep_15s_ease-in-out_infinite]">
                <img src="/images/pinup1.png" className="h-full w-full" />
              </div>
              <div className="flex flex-col absolute top-20 right-0 z-100">
                <h4 className="text-4xl text-customYellow font-[Starduster] drop-shadow-lg animate-[beep1_10s_ease-in-out_infinite]">Good Luck!</h4>
                <h4 className="text-4xl text-customYellow font-[Starduster] drop-shadow-lg animate-[beep2_10s_ease-in-out_infinite]">幸運を祈る</h4>
              </div>
            </div>
            <div className="w-full h-12 bg-customYellow absolute z-100 bottom-20 overflow-hidden flex items-center">
              <Marquee pauseOnHover speed={80} gradient={false}>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ETH: 1.5  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  BTC: 1.2  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ALGO: 1.1  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ETH: 1.5  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  BTC: 1.2  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ALGO: 1.1  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ETH: 1.5  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  BTC: 1.2  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ALGO: 1.1  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ETH: 1.5  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  BTC: 1.2  ///
                </h4>
                <h4 className="text-2xl font-bold text-zinc-800 font-[Starduster] mx-4">
                  ALGO: 1.1  ///
                </h4>
              </Marquee>
            </div>
          </div>
        </div>
        {/* timestamp: 20:00 */}

        <div className="w-full h-screen">
          <Image
            src="/images/background.png"
            layout="fill"
            objectFit="cover"
          />
        </div>
      </main>

      {/* about */}
      <div className="w-full bg-customBlue py-8">
        <div className="w-full">
          <div className="w-full max-w-7xl mx-auto flex justify-center items-center flex-col md:flex-row mb-4 bg-zinc-800 rounded-xl border-4 border-customLightBlue drop-shadow-xl">
            <div className="w-full md:w-1/2 p-4">
              <h3 className="text-2xl text-customRed font-[Starduster]">importAnt!</h3>
              <p className="text-white">
                Sokudo Lottery uses testnet Ether only and is deployed to the Rinkeby testnet.
              </p>
              <p className="text-white">
                No real value is required to participate in the lottery.
              </p>
              <p className="text-white">
                No real value is to be gained or distributed as the prize for winning and/or participating in this lottery.
              </p>
              <p className="text-white">
                This project exists for demonstration purposes only.
              </p>
            </div>
            <div className="w-full md:w-1/2 p-4">
              <div className="w-full flex justify-center items-center">
                <div className="w-1/2 flex justify-center items-center">
                  <Image
                    src="/images/warning.png"
                    width={100}
                    height={100}
                  />
                </div>
                <div className="w-1/2">
                  <div className="h-8 overflow-hidden mb-4">
                    <div className="animate-[warningMove2_10s_ease-in_infinite_alternate]">
                      <h4 className="text-4xl text-customRed font-[Starduster]">wArning</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">警告</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">WArnung</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">Figyelem</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">경고</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">upozorenje</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">uyAri</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">Avviso</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">चेतावनी</h4>
                      <h4 className="text-4xl text-customRed font-[Starduster]">bridinAjums</h4>
                    </div>
                  </div>
                  <div className="h-16 overflow-hidden mb-4">
                    <div className="animate-[warningMove_10s_ease-in_infinite_alternate]">
                      <h5 className="text-2xl text-customRed font-[Starduster]">for testing purposes only</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">テスト目的のみ<br /></h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">nur zu Testzwecken</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">csAk tesztelés céljából</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">테스트 목적으로만<br /><br /></h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">sAmo zA svrhe testirAnjA</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">sAdece test AmAçli</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">solo A scopo di test</h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">केवल परीक्षण के उद्देश्य<br /><br /></h5>
                      <h5 className="text-2xl text-customRed font-[Starduster]">tikAi testešAnAs nolukiem</h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* instructions */}
        <div className="w-full">
          <div className="w-full max-w-7xl mx-auto flex flex-col md:flex-row mb-4 p-4 rounded-xl border-4 border-customLightBlue drop-shadow-xl bg-white">
            <div className="w-full md:w-1/2">

              <div className="w-full flex flex-col mb-4">
                <h4 className="text-2xl font-[Starduster] text-customRed">lAnguage Selection</h4>
                <div className="w-full flex">
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(1)}>En</button>
                  <button className="p-2 px-4 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(2)}>Ja</button>
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(3)}>Hi</button>
                  <button className="p-2 px-4 mr-2 bg-customYellow text-customPurple font-bold rounded transition duration-300 hover:bg-customPurple hover:text-customYellow" onClick={() => setDescLang(4)}>Ur</button>
                </div>
              </div>

              { descLang == 1 &&
              <div className="w-full">
                <h3 className="text-2xl text-customPurple font-[Starduster]">How to Use</h3>
                <p>
                  You are going to need a MetaMask wallet, if you don't have one installed yet you can download it here:
                </p>
                <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
                <p>
                  Sokudo Lottery is connected to the Rinkeby ether testnet, so you should connect your MetaMask wallet to
                  Rinkeby testnet.
                </p>
                <p>
                  Sokudo Lottery uses testnet Ether which you can get in one of the Rinkeby testnet faucets:
                </p>
                <ul className="mb-4">
                  <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
                  <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
                  <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
                </ul>
                <p>
                  Once you get test Ether you are ready to play!
                </p>
                <p className="mb-4">
                  Click here to go to lottery, good luck!
                </p>
                <div className="w-1/2 md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
                  <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                    <p className="text-customYellow text-2xl text-center">To Lottery</p>
                  </Link>
                </div>
              </div>
            }

            { descLang == 2 &&
            <div className="w-full">
              <h3 className="text-2xl text-customPurple font-[Starduster]">それの使い方</h3>
              <p>
                MetaMaskウォレットが必要になります, <br />こちらからダウンロードできます:
              </p>
              <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
              <p>
                宝くじはネットワークRinkebyに接続されています, <br />
                MetaMaskをRinkebyネットワークに接続します.
              </p>
              <p>
                宝くじはtest Etherを使用します<br />
                ここで test Ether を入手できます:
              </p>
              <ul className="mb-4">
                <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
                <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
                <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
              </ul>
              <p>
                これで、プレイする準備ができました!
              </p>
              <p className="mb-4">
                宝くじに行くにはここをクリックしてください!
              </p>
              <div className="w-1/2 md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
                <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                  <p className="text-customYellow text-2xl text-center">宝くじに行く</p>
                </Link>
              </div>
            </div>
          }

          { descLang == 3 &&
          <div className="w-full">
            <h3 className="text-2xl text-customPurple font-[Starduster]">कैसे इस्तेमाल करे</h3>
            <p>
              आपको मेटामास्क वॉलेट की आवश्यकता होगी, <br />
              आप द्वारा इसे यहां पर डाउनलोड किया जा सकता है:
            </p>
            <a href="https://metamask.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
            <p>
              सोकुडो लॉटरी रिकेबी टेस्टनेट से जुड़ी है, <br />
              अपने मेटामास्क को रिंकीबी से कनेक्ट करें
            </p>
            <p>
              सोकुडो लॉटरी टेस्ट ईथर का उपयोग करती है, <br />
              आप इसे यहां पा सकते हैं:
            </p>
            <ul className="mb-4">
              <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
              <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
              <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
            </ul>
            <p>
              अब, आप खेलने के लिए तैयार हैं!
            </p>
            <p className="mb-4">
              लॉटरी में जाने के लिए यहां क्लिक करें, आप सौभाग्यशाली हों!
            </p>
            <div className="w-1/2 md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
              <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                <p className="text-customYellow text-2xl text-center">लॉटरी में जाना</p>
              </Link>
            </div>
          </div>
        }

        { descLang == 4 &&
        <div className="w-full text-right">
          <h3 className="text-2xl text-customPurple font-[Starduster] text-right">استعمال کرنے کا طریقہ</h3>
          <p className="text-right">
            پ کو میٹا ماسک والیٹ کی <br />
            ضرورت ہوگی۔ <br />
            آپ اسے یہاں سے ڈاؤن لوڈ کر<br />
            سکتے ہیں۔
          </p>
          <a href="https://metamask.io/" className="text-right text-customPurple font-bold transition duration-300 hover:text-customBlue">metamask.io</a>
          <p>
            لاٹری رنکیبی ٹیسٹ نیٹ ورک <br />
            سے منسلک ہے۔ <br />
            اپنے Metamask کو <br />
            Rinkeby سے جوڑیں۔
          </p>
          <p>
            یہاں ٹیسٹ ایتھر حاصل کریں۔
          </p>
          <ul className="mb-4">
            <li><a href="https://faucet.rinkeby.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucet.rinkeby.io</a></li>
            <li><a href="https://rinkeby.faucet.epirus.io/" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">rinkeby.faucet.epirus.io</a></li>
            <li><a href="https://faucets.chain.link/rinkeby" className="text-customPurple font-bold transition duration-300 hover:text-customBlue">faucets.chain.link/rinkeby</a></li>
          </ul>
          <p>
            اب آپ کھیلنے کے لیے تیار ہیں۔
          </p>
          <p className="mb-4">
            لاٹری میں جانے کے لیے یہاں <br />
            کلک کریں۔
          </p>
          <div className="w-full flex justify-end">
            <div className="w-1/2 md:w-1/3 md:mr-4 p-2 bg-customPurple font-[Starduster] text-2xl cursor-pointer drop-shadow-lg transition duration-300 hover:bg-customLightPurple">
              <Link href="/lotterypage" className="font-[Starduster] cursor-pointer text-customYellow">
                <p className="text-customYellow text-2xl text-center">لاٹری میں جاؤ</p>
              </Link>
            </div>
          </div>
        </div>
      }


            </div>
          </div>
        </div>

        {/* description */}
        <div className="w-full">
          <div className="w-full max-w-7xl mx-auto flex flex-col md:flex-row pb-4 p-4">
            <div className="w-full md:w-1/2">
              <h3 className="text-2xl text-customYellow font-[Starduster]">Description</h3>
              <p>
                This project is made using smart contract written in Solidity and Truffle. Frontend is made with Next.Js and Tailwing css
              </p>
              <div className="bg-transparent">
                <AutoplaySlider
                    play={true}
                    cancelOnInteraction={false} // should stop playing on user interaction
                    interval={3000}
                    organicArrows={false}
                    bullets={false}
                    sliderHeightPercentage={10}
                    className="h-20"
                  >
                  <div className="bg-transparent" data-src="/images/pinup1.png" />
                  <div className="bg-transparent" data-src="/images/pinup1.png" />
                  <div className="bg-transparent" data-src="/images/pinup1.png" />
                </AutoplaySlider>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full bg-customPurple">
        <Footer />
      </div>
    </div>
  )
}
