import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import 'bulma/css/bulma.css';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Lottery Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {/* navbar */}
        <nav className="navbar mt-4 mb-4">
          <div className="container">
            <div className="navbar-brand">
                <h1 className="underline">Ether Lotter</h1>
            </div>
            <div className="navbar-end">
              <button className="button is-link">
                Connect Wallet
              </button>
            </div>
          </div>
        </nav>

        {/* main content */}
        <div className="container">
          <section className="mt-5">
            <div className="columns">
              <div className="column is-two-thirds">
                <section className="mt-5">
                  <p>Enter Lottery by sending 0.01 Ether</p>
                  <button className="button is-link is-large is-light mt-3">
                    Play Now!
                  </button>
                  <h4>Give it a try!</h4>
                  <h4>頑張って</h4>
                </section>
                <section className="mt-6">
                  <p>Admin Only - Pick Winnder</p>
                  <button className="button is-primary is-large is-light mt-3">
                    Pick Winner
                  </button>
                </section>
              </div>
              <div className="column is-one-third">
                <p>Lottery Info</p>
                <section className="mt-5">
                  <div className="card">
                    <div className="card-content">
                      <div className="content">
                        <h2>Lottery History</h2>
                        <h2>沿革</h2>
                        <div className="history-entry">
                          <div>Lottery #1 Winner: </div>
                          <div>勝者</div>
                          <div>
                            <a href="" target="_blank">7585869695947373636346586896769</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <section className="mt-5">
                  <div className="card">
                    <div className="card-content">
                      <div className="content">
                        <h2>Players (1)</h2>
                        <h2>プレイヤー</h2>
                        <div>
                          <a href="" target="_blank">7585869695947373636346586896769</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <section className="mt-5">
                  <div className="card">
                    <div className="card-content">
                      <div className="content">
                        <h2>Pot</h2>
                        <h2>総計</h2>
                        <p>10 Ether</p>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </section>
        </div>
        {/* timestamp: 20:00 */}

      </main>

      <footer className={styles.footer}>
        <p>&copy; 2022 Lottery Dapp</p>
      </footer>
    </div>
  )
}
